// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Food struct {
	FdcID          int64
	Description    string
	DatasetSource  string
	ProteinG       float64
	CarbsG         float64
	FatG           float64
	Kcal           float64
	UpdatedAt      time.Time
	DescriptionTsv interface{}
}

type IngestRun struct {
	ID            int64
	StartedAt     time.Time
	FinishedAt    time.Time
	Source        string
	Datasets      []string
	RowsStaged    int32
	RowsUpserted  int32
	DurationMs    int64
	RowsSkipped   int32
	RowsMalformed int32
}

type StagingFood struct {
	FdcID         int64
	Description   string
	DatasetSource string
	ProteinG      float64
	CarbsG        float64
	FatG          float64
	Kcal          float64
}
