// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	FdcID         int64
	Description   string
	DatasetSource string
	ProteinG      pgtype.Numeric
	CarbsG        pgtype.Numeric
	FatG          pgtype.Numeric
	Kcal          pgtype.Numeric
	UpdatedAt     pgtype.Timestamptz
}

type IngestRun struct {
	ID           int64
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	Source       string
	Datasets     []string
	RowsStaged   int32
	RowsUpserted int32
	DurationMs   int64
}

type StagingFood struct {
	FdcID         int64
	Description   string
	DatasetSource string
	ProteinG      pgtype.Numeric
	CarbsG        pgtype.Numeric
	FatG          pgtype.Numeric
	Kcal          pgtype.Numeric
}
