// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	FdcID         int64
	Description   string
	DatasetSource string
	ProteinG      pgtype.Numeric
	CarbsG        pgtype.Numeric
	FatG          pgtype.Numeric
	Kcal          pgtype.Numeric
	UpdatedAt     time.Time
}

type IngestRun struct {
	ID            int64
	StartedAt     time.Time
	FinishedAt    time.Time
	Source        string
	Datasets      []string
	RowsStaged    int32
	RowsUpserted  int32
	DurationMs    int64
	RowsSkipped   int32
	RowsMalformed int32
}

type StagingFood struct {
	FdcID         int64
	Description   string
	DatasetSource string
	ProteinG      pgtype.Numeric
	CarbsG        pgtype.Numeric
	FatG          pgtype.Numeric
	Kcal          pgtype.Numeric
}
