// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertIngestRun = `-- name: InsertIngestRun :exec
INSERT INTO ingest_runs (
    started_at, finished_at, source, datasets, rows_staged, rows_upserted, duration_ms
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertIngestRunParams struct {
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	Source       string
	Datasets     []string
	RowsStaged   int32
	RowsUpserted int32
	DurationMs   int64
}

func (q *Queries) InsertIngestRun(ctx context.Context, arg InsertIngestRunParams) error {
	_, err := q.db.Exec(ctx, insertIngestRun,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Source,
		arg.Datasets,
		arg.RowsStaged,
		arg.RowsUpserted,
		arg.DurationMs,
	)
	return err
}
