// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const insertIngestRun = `-- name: InsertIngestRun :exec
INSERT INTO ingest_runs (
    started_at, finished_at, source, datasets, rows_staged, rows_upserted,
    rows_skipped, rows_malformed, duration_ms
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertIngestRunParams struct {
	StartedAt     time.Time
	FinishedAt    time.Time
	Source        string
	Datasets      []string
	RowsStaged    int32
	RowsUpserted  int32
	RowsSkipped   int32
	RowsMalformed int32
	DurationMs    int64
}

func (q *Queries) InsertIngestRun(ctx context.Context, arg InsertIngestRunParams) error {
	_, err := q.db.Exec(ctx, insertIngestRun,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Source,
		arg.Datasets,
		arg.RowsStaged,
		arg.RowsUpserted,
		arg.RowsSkipped,
		arg.RowsMalformed,
		arg.DurationMs,
	)
	return err
}
